package entity;
// Generated 6 f�vr. 2016 21:43:55 by Hibernate Tools 3.6.0

import helper.HQLHelper;
import helper.Helper;
import hibernate.DAO;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.Query;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "config_warehouse")
public class ConfigWarehouse extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "config_warehouse_id_seq")
    @SequenceGenerator(name = "config_warehouse_id_seq", sequenceName = "config_warehouse_id_seq", allocationSize = 1)
    private Integer id;    

    @Column(name = "warehouse")
    private String warehouse;        
    
    @Column(name = "description")
    private String description;

    public ConfigWarehouse() {
    }

    public ConfigWarehouse(String warehouse, String description) {
        this.warehouse = warehouse;
        this.description = description;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }    
    
    public List selectAllWarehouses() {
        Helper.startSession();
        
        Query query = Helper.sess.createQuery(HQLHelper.GET_All_WAREHOUSES);        
        
        Helper.sess.getTransaction().commit();
        return query.list();
    }
    
    public List selectWarehouse(String warehouse) {
        Helper.startSession();
        
        Query query = Helper.sess.createQuery(HQLHelper.GET_WAREHOUSE);
        query.setParameter("warehouse", warehouse);
        
        Helper.sess.getTransaction().commit();
        return query.list();
    }        
    
    
}
