package entity;
// Generated 6 f�vr. 2016 21:43:55 by Hibernate Tools 3.6.0

import __main__.GlobalMethods;
import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "config_barcode")
public class ConfigBarcode extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "config_barcode_id_seq")
    @SequenceGenerator(name = "config_barcode_id_seq", sequenceName = "config_barcode_id_seq", allocationSize = 1)
    private Integer id;

    /*keyword to select a type of barcode_pattern in the code */
    @Column(name = "key_word")
    private String keyWord;

    @Column(name = "description")
    private String description;

    @Column(name = "barcode_pattern")
    private String barcodePattern;

    @Column(name = "harness_part")
    private String harnessPart;

    @Column(name = "harness_type")
    private String harness_type;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "write_time")
    private Date writeTime;

    @Column(name = "create_id")
    private int createId;

    @Column(name = "write_id")
    private int writeId;

    @ManyToOne(optional = true, cascade = CascadeType.REFRESH)
    private ConfigUcs ucs;

    public ConfigBarcode() {
    }

    public ConfigBarcode setDefautlVals() {
        /*
         Set default values of this object 
         from the global mode2_context values
         */
        this.createTime = this.writeTime = GlobalMethods.getTimeStamp(null);
        this.createId = this.writeId = PackagingVars.context.getUser().getId();
        return this;
    }

    public ConfigBarcode(String keyWord, String description, String barcodePattern, String harnessPart, String harness_type) {
        this.setDefautlVals();
        this.keyWord = keyWord;
        this.description = description;
        this.barcodePattern = barcodePattern;
        this.harnessPart = harnessPart;
        this.harness_type = harness_type;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getWriteTime() {
        return this.writeTime;
    }

    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    public int getCreateId() {
        return this.createId;
    }

    public void setCreateId(int createId) {
        this.createId = createId;
    }

    public int getWriteId() {
        return this.writeId;
    }

    public void setWriteId(int writeId) {
        this.writeId = writeId;
    }
    
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBarcodePattern() {
        return barcodePattern;
    }

    public void setBarcodePattern(String barcodePattern) {
        this.barcodePattern = barcodePattern;
    }

    public ConfigUcs getConfigUcs() {
        return ucs;
    }

    public void setConfigUcs(ConfigUcs ucs) {
        this.ucs = ucs;
    }

    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    public String getHarnessPart() {
        return harnessPart;
    }

    public void setHarnessPart(String harnessPart) {
        this.harnessPart = harnessPart;
    }

    public String getHarnessType() {
        return harness_type;
    }

    public void setHarnessType(String harness_type) {
        this.harness_type = harness_type;
    }

}
