package entity;
// Generated 6 f�vr. 2016 21:43:55 by Hibernate Tools 3.6.0

import helper.HQLHelper;
import helper.Helper;
import hibernate.DAO;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.Query;

/**
 * ConfigUcs generated by hbm2java
 */
@Entity
@Table(name = "config_booking_type")
public class ConfigBookingType extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "config_booking_id_seq")
    @SequenceGenerator(name = "config_booking_id_seq", sequenceName = "config_booking_id_seq", allocationSize = 1)
    private Integer id;    

    @Column(name = "type")
    private String type;
    
    @Column(name = "code")
    private String code;
    
    @Column(name = "description")
    private String description;

    public ConfigBookingType() {
    }   
    
    public ConfigBookingType(String type, String code, String description) {
        this.type = type;
        this.code = code;
        this.description = description;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    
    public List selectAllBookingType() {
        Helper.startSession();
        
        Query query = Helper.sess.createQuery(HQLHelper.GET_All_BOOKING_TYPE);        
        
        Helper.sess.getTransaction().commit();
        return query.list();
    }
    
    public List selectBookingType(String type) {
        Helper.startSession();
        
        Query query = Helper.sess.createQuery(HQLHelper.GET_BOOKING_TYPE);
        query.setParameter("type", type);
        
        Helper.sess.getTransaction().commit();
        return query.list();
    }
    
    public List selectBookingTypeByCode(String code) {
        Helper.startSession();
        
        Query query = Helper.sess.createQuery(HQLHelper.GET_BOOKING_TYPE_BY_CODE);
        query.setParameter("code", code);
        
        Helper.sess.getTransaction().commit();
        return query.list();
    }
    
    
}
