/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import __main__.GlobalMethods;
import hibernate.DAO;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * HisPalletPrint generated by hbm2java
 */
@Entity
@Table(name = "dispatch_note_line")
public class DispatchNoteLine extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "dispatch_line_id_seq")
    @SequenceGenerator(name = "dispatch_line_id_seq", sequenceName = "dispatch_line_id_seq", allocationSize = 1)
    private Integer id;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Column(name = "create_id")
    private int createId;
    
    @Column(name = "m_user")
    private String user;

    @Column(name = "advice_note_num")
    private String adviceNoteNum;

    @Column(name = "fors_advice")
    private String forsAdviceNote;

    @Column(name = "fors_hp")
    private String forsHp;

    @Column(name = "prod_hp")
    private String prodHp;

    @Column(name = "fors_qty")
    private String forsQty;

    @Column(name = "prod_qty")
    private String prodQty;

    @Column(name = "fors_label_id")
    private String forsLabelId;

    @ManyToOne(optional = true, cascade = CascadeType.REFRESH)
    private DispatchNote dispatchNote;

    public DispatchNoteLine() {
    }

    public DispatchNoteLine(int createId, String user, String adviceNote, String forsAdviceNote, String forsHp, String forsQty, String forsLabelId, String prodHp, String prodQty) {
        this.createTime = GlobalMethods.getTimeStamp(null);
        this.createId = createId;
        this.user = user;
        this.adviceNoteNum = adviceNote;
        this.forsAdviceNote = forsAdviceNote;
        this.forsHp = forsHp;
        this.prodHp = prodHp;
        this.forsQty = forsQty;
        this.prodQty = prodQty;
        this.forsLabelId = forsLabelId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public int getCreateId() {
        return createId;
    }

    public void setCreateId(int createId) {
        this.createId = createId;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }       
    
    public String getAdviceNoteNum() {
        return adviceNoteNum;
    }

    public void setAdviceNoteNum(String adviceNoteNum) {
        this.adviceNoteNum = adviceNoteNum;
    }

    public String getForsAdviceNote() {
        return forsAdviceNote;
    }

    public void setForsAdviceNote(String forsAdviceNote) {
        this.forsAdviceNote = forsAdviceNote;
    }

    public String getForsHp() {
        return forsHp;
    }

    public void setForsHp(String forsHp) {
        this.forsHp = forsHp;
    }

    public String getForsQty() {
        return forsQty;
    }

    public void setForsQty(String forsQty) {
        this.forsQty = forsQty;
    }

    public String getForsLabelId() {
        return forsLabelId;
    }

    public void setForsLabelId(String forsLabelId) {
        this.forsLabelId = forsLabelId;
    }

    public String getProdHp() {
        return prodHp;
    }

    public void setProdHp(String prodHp) {
        this.prodHp = prodHp;
    }

    public String getProdQty() {
        return prodQty;
    }

    public void setProdQty(String prodQty) {
        this.prodQty = prodQty;
    }

    public DispatchNote getDispatchNote() {
        return dispatchNote;
    }

    public void setDispatchNote(DispatchNote dispatchNote) {
        this.dispatchNote = dispatchNote;
    }

}
