package entity;
// Generated 30 janv. 2016 21:44:13 by Hibernate Tools 3.6.0

import __main__.GlobalMethods;
import hibernate.DAO;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 * HisLogin generated by hbm2java
 */
@Entity
@Table(name = "his_login")
public class HisLogin extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "his_login_id_seq")
    @SequenceGenerator(name = "his_login_id_seq", sequenceName = "his_login_id_seq", allocationSize = 1)    
    private Integer id;
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "write_time")
    private Date writeTime;

    @Column(name = "create_id")
    private int createId;

    @Column(name = "write_id")
    private int writeId;
    
    @Column(name = "message")
    private String message;

    public HisLogin() {
    }

    public HisLogin(int createId, int writeId, String message) {
        this.createTime = GlobalMethods.getTimeStamp(null);
        this.writeTime = GlobalMethods.getTimeStamp(null);
        this.createId = createId;
        this.writeId = writeId;
        this.message = message;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getWriteTime() {
        return this.writeTime;
    }

    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    public int getCreateId() {
        return this.createId;
    }

    public void setCreateId(int createId) {
        this.createId = createId;
    }

    public int getWriteId() {
        return this.writeId;
    }

    public void setWriteId(int writeId) {
        this.writeId = writeId;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void create(Session session, String message, int user_id) {

        try {
            session.beginTransaction();
            HisLogin hislogin = new HisLogin(user_id, user_id, message);
            id = (Integer) session.save(hislogin);

            //Save the employee in database
            session.save(hislogin);
            //Commit the transaction
            session.getTransaction().commit();
        } catch (HibernateException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        System.out.println("Rows inserted in table affected: " + id);
    }

}
