package entity;
// Generated 6 f�vr. 2016 21:43:55 by Hibernate Tools 3.6.0

import __main__.GlobalMethods;
import gui.packaging.PackagingVars;
import hibernate.DAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * ScheduleEntry generated by hbm2java
 */
@Entity
@Table(name = "schedule_entry")
public class ScheduleEntry extends DAO implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "schedule_entry_id_seq")
    @SequenceGenerator(name = "schedule_entry_id_seq", sequenceName = "schedule_entry_id_seq", allocationSize = 1)
    private Integer id;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "create_time")
    private Date createTime;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name = "write_time")
    private Date writeTime;

    @Column(name = "create_id")
    private int createId;

    @Column(name = "write_id")
    private int writeId;

    @Column(name = "harness_type")
    private String harnessType;

    @Column(name = "harness_part")
    private String harnessPart;

    @Column(name = "harness_index")
    private String harnessIndex;

    @Column(name = "pack_type")
    private String packType;

    @Column(name = "pack_size")
    private int packSize;

    @Column(name = "supplier_part_number")
    private String supplierPartNumber;

    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(name = "planned_day")
    private Date plannedDay;

    @Column(name = "start_hour")
    private String startHour;

    @Column(name = "start_minute")
    private String startMinute;

    @Column(name = "end_hour")
    private String endHour;

    @Column(name = "end_minute")
    private String endMinute;

    @Column(name = "planned_pack")
    private float plannedPack;

    @Column(name = "total_planned")
    private float totalPlanned;

    @Column(name = "total_produced", nullable = true)
    private float totalProduced;

    @Column(name = "total_picked", nullable = true)
    private float totalPicked;

    @Column(name = "total_remaining", nullable = true)
    private float totalRemaining;

    @Column(name = "shift_name")
    private String shiftName;

    @ManyToOne(optional = false, cascade = CascadeType.ALL)
    private ConfigShift shift;

    @Column(name = "entry_state", nullable = true)
    private String entryState;

    @Column(name = "entry_state_code", nullable = true)
    private String entryStateCode;

    @Column(name = "comment", nullable = true)
    private String comment;

    public ScheduleEntry() {
    }

    public final void setDefautlVals() {
        /*
         Set default values of this object 
         from the global mode2_context values
         */
        this.createTime = this.writeTime = GlobalMethods.getTimeStamp(null);
        this.createId = this.writeId = PackagingVars.context.getUser().getId();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getWriteTime() {
        return writeTime;
    }

    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    public int getCreateId() {
        return createId;
    }

    public void setCreateId(int createId) {
        this.createId = createId;
    }

    public int getWriteId() {
        return writeId;
    }

    public void setWriteId(int writeId) {
        this.writeId = writeId;
    }

    public String getHarnessType() {
        return harnessType;
    }

    public void setHarnessType(String harnessType) {
        this.harnessType = harnessType;
    }

    public String getHarnessPart() {
        return harnessPart;
    }

    public void setHarnessPart(String harnessPart) {
        this.harnessPart = harnessPart;
    }

    public String getHarnessIndex() {
        return harnessIndex;
    }

    public void setHarnessIndex(String harnessIndex) {
        this.harnessIndex = harnessIndex;
    }

    public String getPackType() {
        return packType;
    }

    public void setPackType(String packType) {
        this.packType = packType;
    }

    public int getPackSize() {
        return packSize;
    }

    public void setPackSize(int packSize) {
        this.packSize = packSize;
    }

    public String getSupplierPartNumber() {
        return supplierPartNumber;
    }

    public void setSupplierPartNumber(String supplierPartNumber) {
        this.supplierPartNumber = supplierPartNumber;
    }

    public Date getPlannedDay() {
        return plannedDay;
    }

    public void setPlannedDay(Date plannedDay) {
        this.plannedDay = plannedDay;
    }

    public String getStartHour() {
        return startHour;
    }

    public void setStartHour(String startHour) {
        this.startHour = startHour;
    }

    public String getStartMinute() {
        return startMinute;
    }

    public void setStartMinute(String startMinute) {
        this.startMinute = startMinute;
    }

    public String getEndHour() {
        return endHour;
    }

    public void setEndHour(String endHour) {
        this.endHour = endHour;
    }

    public String getEndMinute() {
        return endMinute;
    }

    public void setEndMinute(String endMinute) {
        this.endMinute = endMinute;
    }

    public float getPlannedPack() {
        return plannedPack;
    }

    public void setPlannedPack(float plannedPack) {
        this.plannedPack = plannedPack;
    }

    public float getTotalPlanned() {
        return totalPlanned;
    }

    public void setTotalPlanned(float totalPlanned) {
        this.totalPlanned = totalPlanned;
    }

    public float getTotalPicked() {
        return totalPicked;
    }

    public void setTotalPicked(float totalPicked) {
        this.totalPicked = totalPicked;
    }

    public float getTotalProduced() {
        return totalProduced;
    }

    public void setTotalProduced(float totalProduced) {
        this.totalProduced = totalProduced;
    }

    public float getTotalRemaining() {
        return totalRemaining;
    }

    public void setTotalRemaining(float totalRemaining) {
        this.totalRemaining = totalRemaining;
    }

    public ConfigShift getShift() {
        return shift;
    }

    public void setShift(ConfigShift shift) {
        this.shift = shift;
    }

    public String getShiftName() {
        return shiftName;
    }

    public void setShiftName(String shiftName) {
        this.shiftName = shiftName;
    }

    public String getEntryState() {
        return entryState;
    }

    public void setEntryState(String entryState) {
        this.entryState = entryState;
    }

    public String getEntryStateCode() {
        return entryStateCode;
    }

    public void setEntryStateCode(String entryStateCode) {
        this.entryStateCode = entryStateCode;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @SuppressWarnings("UnusedAssignment")
    public String getCreateTimeString(String format) {
        if (format == null) {
            format = "yyyy-MM-dd HH:mm:ss";
        }
        DateFormat df = new SimpleDateFormat(format);
        return df.format(this.createTime);
    }

    @Override
    public String toString() {
        return "ScheduleEntry{" + ""
                + "\n id=" + id + ","
                + "\n createTime=" + createTime + ","
                + "\n writeTime=" + writeTime + ","
                + "\n createId=" + createId + ","
                + "\n writeId=" + writeId + ","
                + "\n harnessType=" + harnessType + ","
                + "\n harnessPart=" + harnessPart + ","
                + "\n harnessIndex=" + harnessIndex + ","
                + "\n packType=" + packType + ","
                + "\n packSize=" + packSize + ","
                + "\n supplierPartNumber=" + supplierPartNumber + ","
                + "\n plannedDay=" + plannedDay + ","
                + "\n startHour=" + startHour + ","
                + "\n startMinute=" + startMinute + ","
                + "\n endHour=" + endHour + ","
                + "\n endMinute=" + endMinute + ","
                + "\n plannedPack=" + plannedPack + ","
                + "\n totalPlanned=" + totalPlanned + ","
                + "\n totalProduced=" + totalProduced + ","
                + "\n totalPicked=" + totalPicked + ","
                + "\n totalRemaining=" + totalRemaining + ","
                + "\n shiftName=" + shiftName + ","
                + "\n shift=" + shift + ","
                + "\n entryState=" + entryState + ","
                + "\n entryStateCode=" + entryStateCode + ","
                + "\n comment=" + comment + "\n}";
    }

}
