package gui.packaging.reports;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import __main__.GlobalVars;
import helper.Helper;
import helper.HQLHelper;
import entity.BaseContainer;
import entity.BaseHarness;
import entity.DropBaseHarness;
import gui.packaging.PackagingVars;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import org.hibernate.Query;

/**
 *
 * @author user
 */
public class PACKAGING_UI0012_HarnessDetails extends javax.swing.JDialog {

    Vector<String> searchResult_table_header = new Vector<String>();
    Vector searchResult_table_data = new Vector();
    BaseHarness bh;
    BaseContainer bc;
    boolean drop;

    //ERROR MESSAGES
    String ERR_HARNESS_NOT_FOUND = "Harness Not Found !";
    String ERR_REQUIRED_COMMENT = "Drop comment required !";
    String ERR_PALLET_STATE_ERROR = "Drop not allowed ! Pallet must be OPEN to drop the harness !";

    //SUCCESS MESSAGES
    String OK_HARNESS_DROPPED = "Harness dropped successfully !";

    /**
     * Creates new form UI0010_PalletDetails
     *
     * @param parent
     * @param modal
     * @param drop
     */
    public PACKAGING_UI0012_HarnessDetails(java.awt.Frame parent, boolean modal, boolean drop) {
        super(parent, modal);

        initComponents();
        this.setResizable(false);
        Helper.centerJDialog(this);
        success_lbl.setVisible(false);
        if (drop) {
            this.drop = true;
            dropComment_lbl.setVisible(true);
            dropComment_txtbox.setVisible(true);
            drop_btn.setVisible(true);
        } else {
            this.drop = false;
            dropComment_lbl.setVisible(false);
            dropComment_txtbox.setVisible(false);
            drop_btn.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user_txtbox = new javax.swing.JTextField();
        harnessCounter_txtbox = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        error_lbl = new javax.swing.JLabel();
        drop_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dropComment_txtbox = new javax.swing.JTextArea();
        dropComment_lbl = new javax.swing.JLabel();
        error_lbl1 = new javax.swing.JLabel();
        success_lbl = new javax.swing.JLabel();
        harnessPart_txtbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        harnessCreateTime_txtBox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        create_user_txtbox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        startTime_txtbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qtyExptected_txtbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        qtyRead_txtbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        completeTime_txtbox = new javax.swing.JTextField();
        workingTime_txtbox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        packType_txtbox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        state_txtbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        index_txtbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        supplierPartNumber_txtbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        palletNumber_txtbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pallet Details");
        setType(java.awt.Window.Type.UTILITY);

        jLabel2.setText("User Number");

        user_txtbox.setEditable(false);
        user_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        user_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_txtboxActionPerformed(evt);
            }
        });

        harnessCounter_txtbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        harnessCounter_txtbox.setForeground(new java.awt.Color(0, 0, 204));
        harnessCounter_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harnessCounter_txtboxActionPerformed(evt);
            }
        });
        harnessCounter_txtbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                harnessCounter_txtboxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                harnessCounter_txtboxKeyTyped(evt);
            }
        });

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/edit-find.png"))); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Harness counter");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Harness Details");

        error_lbl.setForeground(java.awt.Color.red);

        drop_btn.setBackground(java.awt.Color.red);
        drop_btn.setForeground(new java.awt.Color(255, 255, 255));
        drop_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/edit-delete.png"))); // NOI18N
        drop_btn.setText("Drop");
        drop_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drop_btnActionPerformed(evt);
            }
        });

        dropComment_txtbox.setColumns(20);
        dropComment_txtbox.setRows(3);
        jScrollPane1.setViewportView(dropComment_txtbox);

        dropComment_lbl.setText("Drop comment :");

        error_lbl1.setForeground(java.awt.Color.red);

        success_lbl.setBackground(java.awt.SystemColor.info);
        success_lbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        success_lbl.setForeground(new java.awt.Color(0, 102, 51));
        success_lbl.setText(" ");

        harnessPart_txtbox.setEditable(false);
        harnessPart_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        harnessPart_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harnessPart_txtboxActionPerformed(evt);
            }
        });

        jLabel8.setText("Harness Part");

        harnessCreateTime_txtBox.setEditable(false);
        harnessCreateTime_txtBox.setBackground(new java.awt.Color(255, 255, 255));
        harnessCreateTime_txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harnessCreateTime_txtBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Create Time");

        create_user_txtbox.setEditable(false);
        create_user_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        create_user_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_user_txtboxActionPerformed(evt);
            }
        });

        jLabel17.setText("Create User");

        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/edit-clear.png"))); // NOI18N
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(success_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(harnessPart_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(create_user_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(harnessCreateTime_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dropComment_lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(error_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 396, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(error_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(harnessCounter_txtbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(drop_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(success_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(harnessCounter_txtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(drop_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropComment_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error_lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(create_user_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harnessPart_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harnessCreateTime_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setToolTipText("Pallet Details");
        jPanel2.setName(""); // NOI18N
        jPanel2.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Pallet Details");

        startTime_txtbox.setEditable(false);
        startTime_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        startTime_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTime_txtboxActionPerformed(evt);
            }
        });

        jLabel6.setText("Start Time");

        qtyExptected_txtbox.setEditable(false);
        qtyExptected_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        qtyExptected_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyExptected_txtboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Pallet number");

        jLabel4.setText("Quantity Read");

        qtyRead_txtbox.setEditable(false);
        qtyRead_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        qtyRead_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyRead_txtboxActionPerformed(evt);
            }
        });

        jLabel7.setText("Complete Time");

        completeTime_txtbox.setEditable(false);
        completeTime_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        completeTime_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeTime_txtboxActionPerformed(evt);
            }
        });

        workingTime_txtbox.setEditable(false);
        workingTime_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        workingTime_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingTime_txtboxActionPerformed(evt);
            }
        });

        jLabel12.setText("Working time (min)");

        packType_txtbox.setEditable(false);
        packType_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        packType_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packType_txtboxActionPerformed(evt);
            }
        });

        jLabel11.setText("Pack Type");

        state_txtbox.setEditable(false);
        state_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        state_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state_txtboxActionPerformed(evt);
            }
        });

        jLabel5.setText("State");

        index_txtbox.setEditable(false);
        index_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        index_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                index_txtboxActionPerformed(evt);
            }
        });

        jLabel9.setText("Index");

        supplierPartNumber_txtbox.setEditable(false);
        supplierPartNumber_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        supplierPartNumber_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierPartNumber_txtboxActionPerformed(evt);
            }
        });

        jLabel10.setText("Supplier Part Number");

        jLabel16.setText("Quantity Expected");

        palletNumber_txtbox.setEditable(false);
        palletNumber_txtbox.setBackground(new java.awt.Color(255, 255, 255));
        palletNumber_txtbox.setForeground(java.awt.Color.blue);
        palletNumber_txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palletNumber_txtboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(startTime_txtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(palletNumber_txtbox))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(163, 163, 163))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(index_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(completeTime_txtbox)
                        .addComponent(qtyExptected_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(qtyRead_txtbox)
                                .addComponent(workingTime_txtbox)
                                .addComponent(jLabel12))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(packType_txtbox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(state_txtbox)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierPartNumber_txtbox)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierPartNumber_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(packType_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(qtyRead_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workingTime_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(state_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyExptected_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completeTime_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palletNumber_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startTime_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_txtboxActionPerformed

    private void harnessPart_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harnessPart_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harnessPart_txtboxActionPerformed

    private void index_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_index_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_index_txtboxActionPerformed

    private void supplierPartNumber_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierPartNumber_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierPartNumber_txtboxActionPerformed

    private void qtyExptected_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyExptected_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyExptected_txtboxActionPerformed

    private void qtyRead_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyRead_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyRead_txtboxActionPerformed

    private void packType_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packType_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packType_txtboxActionPerformed

    private void state_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_state_txtboxActionPerformed

    public void clearSearchBox() {
        //Vider le champs de text scan
        harnessCounter_txtbox.setText("");
        harnessCounter_txtbox.requestFocusInWindow();
    }

    private void searchForHarness(String HarnessCounter) {

        this.clearContainerFieldsValues();

        if (!HarnessCounter.trim().equals("")) {
            //################# Harness Data ####################
            Helper.startSession();
            Query query = Helper.sess.createQuery(HQLHelper.GET_HP_BY_COUNTER);
            query.setParameter("counter", HarnessCounter.trim());
            Helper.sess.getTransaction().commit();
            List result = query.list();

            if (result.isEmpty()) {
                error_lbl.setText(ERR_HARNESS_NOT_FOUND);
            } else {
                //################# Harness Data ####################
                bh = (BaseHarness) result.get(0);
                this.setHernessFieldsValues(bh);
                //################# Container Data ####################
                Helper.startSession();
                query = Helper.sess.createQuery(HQLHelper.GET_CONTAINER_BY_NUMBER);
                query.setParameter("palletNumber", bh.getPalletNumber());
                Helper.sess.getTransaction().commit();
                result = query.list();
                bc = (BaseContainer) result.get(0);
                this.setContainerFieldsValues(bc);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Empty pallet number", "Pallet Number Error", JOptionPane.ERROR_MESSAGE);
            clearSearchBox();
        }

    }

    private void setContainerFieldsValues(BaseContainer bc) {
        
        index_txtbox.setText(bc.getHarnessIndex());
        palletNumber_txtbox.setText(bc.getPalletNumber());
        supplierPartNumber_txtbox.setText(bc.getSupplierPartNumber());
        qtyExptected_txtbox.setText(String.valueOf(bc.getQtyExpected()));
        qtyRead_txtbox.setText(String.valueOf(bc.getQtyRead()));
        packType_txtbox.setText(bc.getPackType());
        state_txtbox.setText(bc.getContainerState());
        startTime_txtbox.setText(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(bc.getStartTime()));
        if (bc.getClosedTime() != null) {
            completeTime_txtbox.setText(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(bc.getClosedTime()));
        }
        workingTime_txtbox.setText(String.valueOf(bc.getWorkTime()));
    }

    private void setHernessFieldsValues(BaseHarness bh) {
        user_txtbox.setText(bh.getUser());
        create_user_txtbox.setText(bh.getCreateUser());
        harnessPart_txtbox.setText(bh.getHarnessPart());
        harnessCreateTime_txtBox.setText(bh.getCreateTimeString(null));
    }

    private void clearContainerFieldsValues() {
        user_txtbox.setText("");
        create_user_txtbox.setText("");
        harnessPart_txtbox.setText("");
        harnessCreateTime_txtBox.setText("");
        index_txtbox.setText("");
        supplierPartNumber_txtbox.setText("");
        qtyExptected_txtbox.setText("");
        qtyRead_txtbox.setText("");
        packType_txtbox.setText("");
        state_txtbox.setText("");
        startTime_txtbox.setText("");
        completeTime_txtbox.setText("");
        workingTime_txtbox.setText("");
        palletNumber_txtbox.setText("");
    }

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        error_lbl.setText("");
        error_lbl1.setText("");
        this.searchForHarness(harnessCounter_txtbox.getText());
    }//GEN-LAST:event_search_btnActionPerformed

    private void harnessCounter_txtboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harnessCounter_txtboxKeyTyped

    }//GEN-LAST:event_harnessCounter_txtboxKeyTyped

    private void harnessCounter_txtboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harnessCounter_txtboxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.searchForHarness(harnessCounter_txtbox.getText());
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();

        } else if (evt.getKeyCode() == KeyEvent.VK_CLEAR) {
            this.harnessCounter_txtbox.setText("");
        }
    }//GEN-LAST:event_harnessCounter_txtboxKeyPressed

    private void startTime_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTime_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTime_txtboxActionPerformed

    private void completeTime_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeTime_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completeTime_txtboxActionPerformed

    private void workingTime_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingTime_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workingTime_txtboxActionPerformed

    private void harnessCounter_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harnessCounter_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harnessCounter_txtboxActionPerformed

    private void harnessCreateTime_txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harnessCreateTime_txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harnessCreateTime_txtBoxActionPerformed

    private void palletNumber_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palletNumber_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palletNumber_txtboxActionPerformed

    private void drop_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drop_btnActionPerformed
        //User can delete only founded harness in a pallet
        error_lbl.setText("");
        error_lbl1.setText("");
        if (dropComment_txtbox.getText().length() == 0) {
            error_lbl1.setText(ERR_REQUIRED_COMMENT);
        } else if (palletNumber_txtbox.getText().length() == 0) {
            error_lbl.setText(ERR_HARNESS_NOT_FOUND);
        } else if (!bc.getContainerState().equals(GlobalVars.PALLET_OPEN)){
            error_lbl.setText(ERR_PALLET_STATE_ERROR);
        }else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    String.format("Are you sure you want to drop the harness [%s] from pallet [%s] ?",
                            harnessCounter_txtbox.getText(),
                            palletNumber_txtbox.getText()),
                    "Drop Harness Confirmation",
                    JOptionPane.WARNING_MESSAGE);
            if (confirmed == 0) {
                //############## MOVE THE HARNESS TO DROP TABLE ################
                DropBaseHarness dbh = new DropBaseHarness(
                        bh.getHarnessPart(),
                        bh.getCounter(),
                        bh.getContainerId(),
                        null,
                        bh.getPalletNumber(),
                        bh.getHarnessType(),
                        dropComment_txtbox.getText(),
                        bh.getStdTime()
                );
                dbh.create(dbh);
                //##############################################################
                
                //########### REMOVE THE HARNESS LABELS FROM ENGINE ############
                Query query = Helper.sess.createQuery(HQLHelper.DEL_LABEL_BY_HP_ID);
                query.setParameter("harnessId", bh.getId());
                int result = query.executeUpdate();
                System.out.println(String.format("Labels removed for harness %s ", result, bh.getId()));
                
                //############ REMOVE THE HARNESS FROM CONTAINER ###############
                query = Helper.sess.createQuery(HQLHelper.DEL_HP_BY_COUNTER);
                query.setParameter("counter", bh.getCounter());
                result = query.executeUpdate();
                System.out.println(String.format("Harness [%s] [%s] removed from pallet %s ", result, bh.getCounter(), bc.getPalletNumber()));
                //##############################################################                

                //############ DECREASE THE PALLET QUANTITY BY 1 ###############
                //Yes                
                if (bc.getQtyRead() > 0) {
                    bc.setQtyRead(bc.getQtyRead()-1); 
                    bc.update(bc);
//                    query = Helper.sess.createQuery(HQLHelper.SET_CONTAINER_QTY_READ);
//                    query.setParameter("qtyRead", bc.getQtyRead() - 1);
//                    query.setParameter("id", bc.getId());
//                    query.executeUpdate();
                    System.out.println(String.format("Pallet %s quantity decreased by 1 piece ", bc.getPalletNumber()));
                }
                //##############################################################

                //Clear UI components
                clearContainerFieldsValues();
                clearSearchBox();
                //Clear comment text box
                dropComment_txtbox.setText("");
                success_lbl.setVisible(true);
                success_lbl.setText(OK_HARNESS_DROPPED);
                //Refresh the main table
                PackagingVars.Packaging_Gui_Mode1.reloadDataTable();
            }
        }
    }//GEN-LAST:event_drop_btnActionPerformed

    private void create_user_txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_user_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_user_txtboxActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed

        harnessCounter_txtbox.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField completeTime_txtbox;
    private javax.swing.JTextField create_user_txtbox;
    private javax.swing.JLabel dropComment_lbl;
    private javax.swing.JTextArea dropComment_txtbox;
    private javax.swing.JButton drop_btn;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JLabel error_lbl1;
    private javax.swing.JTextField harnessCounter_txtbox;
    private javax.swing.JTextField harnessCreateTime_txtBox;
    private javax.swing.JTextField harnessPart_txtbox;
    private javax.swing.JTextField index_txtbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField packType_txtbox;
    private javax.swing.JTextField palletNumber_txtbox;
    private javax.swing.JTextField qtyExptected_txtbox;
    private javax.swing.JTextField qtyRead_txtbox;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField startTime_txtbox;
    private javax.swing.JTextField state_txtbox;
    private javax.swing.JLabel success_lbl;
    private javax.swing.JTextField supplierPartNumber_txtbox;
    private javax.swing.JTextField user_txtbox;
    private javax.swing.JTextField workingTime_txtbox;
    // End of variables declaration//GEN-END:variables
}
