/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.warehouse_dispatch;

import entity.LoadPlanDestination;
import helper.ComboItem;
import helper.HQLHelper;
import helper.Helper;
import java.util.List;
import javax.swing.JComboBox;
import org.hibernate.Query;

/**
 *
 * @author user
 */
public class WAREHOUSE_DISPATCH_UI0007_FIND_PALLET extends javax.swing.JDialog {

    
    private WAREHOUSE_DISPATCH_UI0002_DISPATCH_SCAN parent;

    /**
     * Creates new form WAREHOUSE_OUT_UI0004_NEW_PLAN
     *
     * @param parent
     * @param modal
     * 
     */
    public WAREHOUSE_DISPATCH_UI0007_FIND_PALLET(WAREHOUSE_DISPATCH_UI0002_DISPATCH_SCAN parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;    
        initComponents();
        initGui();
        Helper.centerJDialog(this);
        this.setResizable(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_btn = new javax.swing.JButton();
        time_label2 = new javax.swing.JLabel();
        plan_num_label = new javax.swing.JLabel();
        time_label3 = new javax.swing.JLabel();
        create_user_label = new javax.swing.JLabel();
        time_label1 = new javax.swing.JLabel();
        create_time_label = new javax.swing.JLabel();
        time_label4 = new javax.swing.JLabel();
        deliv_date_label = new javax.swing.JLabel();
        time_label6 = new javax.swing.JLabel();
        state_label = new javax.swing.JLabel();
        time_label7 = new javax.swing.JLabel();
        dest_label = new javax.swing.JLabel();
        palletNumTxt = new javax.swing.JTextField();
        time_label8 = new javax.swing.JLabel();
        time_label5 = new javax.swing.JLabel();
        pile_num_label = new javax.swing.JLabel();
        feedback_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        search_btn.setText("Recherche");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        time_label2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label2.setText("Plan de chargement N° :");

        plan_num_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plan_num_label.setText("-----");

        time_label3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label3.setText("Create user :");

        create_user_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        create_user_label.setText("-----");

        time_label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label1.setText("Date création :");

        create_time_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        create_time_label.setText("--/--/---- --:--");

        time_label4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label4.setText("Date Expédition :");

        deliv_date_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deliv_date_label.setText("--/--/----");

        time_label6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label6.setText("N° Palette");

        state_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        state_label.setText("-----");

        time_label7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label7.setText("Destination :");

        dest_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dest_label.setText("-----");

        time_label8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label8.setText("Status :");

        time_label5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time_label5.setText("Pile :");

        pile_num_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pile_num_label.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(time_label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(time_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(time_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(time_label7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time_label8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time_label5)
                            .addComponent(time_label2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plan_num_label)
                            .addComponent(pile_num_label)
                            .addComponent(create_user_label)
                            .addComponent(create_time_label)
                            .addComponent(deliv_date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dest_label, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_label, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(time_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(palletNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_btn))
                    .addComponent(feedback_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn)
                    .addComponent(palletNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time_label6))
                .addGap(18, 18, 18)
                .addComponent(feedback_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label2)
                    .addComponent(plan_num_label))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label5)
                    .addComponent(pile_num_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label3)
                    .addComponent(create_user_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label1)
                    .addComponent(create_time_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label4)
                    .addComponent(deliv_date_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dest_label)
                    .addComponent(time_label7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state_label)
                    .addComponent(time_label8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        //Creer un nouveau plan de chargement
        initGui();
        
    }//GEN-LAST:event_search_btnActionPerformed

    public static void loadDestsInJbox(List result, JComboBox jbox) {

        if (result.isEmpty()) {
            //JOptionPane.showMessageDialog(null, Helper.ERR0014_NO_PROJECT_FOUND, "Projects Configuration error !", ERROR_MESSAGE);
            System.err.println(Helper.ERR0014_NO_PROJECT_FOUND);
        } else { //Map project data in the list
            for (Object o : result) {
                LoadPlanDestination lp = (LoadPlanDestination) o;
                jbox.addItem(new ComboItem(lp.getDestination(), lp.getDestination()));
            }
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel create_time_label;
    private javax.swing.JLabel create_user_label;
    private javax.swing.JLabel deliv_date_label;
    private javax.swing.JLabel dest_label;
    private javax.swing.JTextField feedback_txt;
    private javax.swing.JTextField palletNumTxt;
    private javax.swing.JLabel pile_num_label;
    private javax.swing.JLabel plan_num_label;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel state_label;
    private javax.swing.JLabel time_label1;
    private javax.swing.JLabel time_label2;
    private javax.swing.JLabel time_label3;
    private javax.swing.JLabel time_label4;
    private javax.swing.JLabel time_label5;
    private javax.swing.JLabel time_label6;
    private javax.swing.JLabel time_label7;
    private javax.swing.JLabel time_label8;
    // End of variables declaration//GEN-END:variables

    private void initGui() {
        palletNumTxt.setText("");
        feedback_txt.setText("");
        plan_num_label.setText("");
        pile_num_label.setText("");
        create_user_label.setText("");
        create_time_label.setText("");
        deliv_date_label.setText("");
        dest_label.setText("");
        state_label.setText("");
    }
}
