/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.warehouse_dispatch;

import entity.LoadPlan;
import entity.LoadPlanDestination;
import entity.LoadPlanDestinationRel;
import gui.warehouse_dispatch.process_reservation.S001_ReservPalletNumberScan;
import gui.warehouse_dispatch.state.WarehouseHelper;
import helper.HQLHelper;
import helper.Helper;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.hibernate.Query;
import ui.UILog;
import ui.error.ErrorMsg;

/**
 *
 * @author user
 */
public final class WAREHOUSE_DISPATCH_UI0004_NEW_PLAN extends javax.swing.JDialog {

    /**
     * Creates new form WAREHOUSE_OUT_UI0004_NEW_PLAN
     */
    public WAREHOUSE_DISPATCH_UI0004_NEW_PLAN(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        initGui();

    }

    private void initGui() {
        Helper.centerJDialog(this);
        this.setResizable(false);
        this.initDestinationsTable();
        disableEditingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deliveryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        destinations_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau plan de chargement");

        ok_btn.setText("OK");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("Annuler");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Delivery Date :");

        jLabel2.setText("Destination :");

        jScrollPane1.setBackground(new java.awt.Color(153, 255, 255));

        destinations_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(destinations_table);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(deliveryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel_btn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deliveryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_btn)
                    .addComponent(cancel_btn))
                .addGap(20, 20, 20))
        );

        getAccessibleContext().setAccessibleName("Nouveau plan de chargement");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        //Get selected destinations 
        String[] selectedDestinations = new String[destinations_table.getRowCount()];
        int i = 0;
        boolean flag = false;
        for (int r = 0; r < destinations_table.getRowCount(); r++) {
            if ((boolean) destinations_table.getValueAt(r, 0) == true) {
                selectedDestinations[i++] = destinations_table.getValueAt(r, 1).toString();
                flag = true;
            }
        }
        if (deliveryDatePicker.getDate() == null) {
            UILog.severe(ErrorMsg.APP_ERR0027[0]);
            UILog.severeDialog(null, ErrorMsg.APP_ERR0027);
        } else if (!flag) {
            UILog.severe(ErrorMsg.APP_ERR0026[0]);
            UILog.severeDialog(null, ErrorMsg.APP_ERR0026);
        } else {
            try {

                Date date = new Date();
                LoadPlan lp = new LoadPlan();
                lp.setCreateId(WarehouseHelper.warehouse_reserv_context.getUser().getId());
                lp.setCreateTime(date);
                lp.setDeliveryTime(deliveryDatePicker.getDate());
                lp.setUser(WarehouseHelper.warehouse_reserv_context.getUser().getFirstName() + " " + WarehouseHelper.warehouse_reserv_context.getUser().getLastName());
                lp.setPlanState(WarehouseHelper.LOAD_PLAN_STATE_OPEN);

                //Save the new plan
                int planId = lp.create(lp);

                //Save the destinations of the plan
                for (String finalDest : selectedDestinations) {
                    if (finalDest != null && !"".equals(finalDest)) {
                        LoadPlanDestinationRel planRel = new LoadPlanDestinationRel(finalDest, planId);
                        planRel.create(planRel);
                    }
                }

                WarehouseHelper.temp_load_plan = lp;
                //Load data into labels
                WarehouseHelper.Dispatch_Gui.loadPlanDataToLabels(lp, selectedDestinations[0]);
                //Load plans JTable
                WarehouseHelper.Dispatch_Gui.reloadPlansData();
                //Auth réussie, Passage à l'état S02 de lecture des fiches Galia               
                WarehouseHelper.warehouse_reserv_context.setState(new S001_ReservPalletNumberScan());
                this.dispose();

            } catch (Exception e) {
                UILog.severe(ErrorMsg.APP_ERR0028[0]);
                UILog.severeDialog(null, ErrorMsg.APP_ERR0028);
            }

        }
    }//GEN-LAST:event_ok_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    public void disableEditingTable() {
        for (int c = 1; c < destinations_table.getColumnCount(); c++) {
            Class<?> col_class = destinations_table.getColumnClass(c);
            if (col_class != Boolean.class) {
                destinations_table.setDefaultEditor(col_class, null);        // remove editor            
            }
        }
    }

    /**
     * Charge les destinations dans le jBox
     */
    public void initDestinationsTable() {
        Helper.startSession();
        Query query = Helper.sess.createQuery(HQLHelper.GET_ALL_FINAL_DESTINATIONS);

        Helper.sess.getTransaction().commit();
        List result = query.list();

        if (result.isEmpty()) {
            UILog.info(ErrorMsg.APP_ERR0025[0]);
            UILog.infoDialog(null, ErrorMsg.APP_ERR0025);
            
            this.dispose();
        } else {

            //Create the destinations table component
            Object[][] data = new Object[result.size()][2];
            for (int i = 0; i < result.size(); i++) {
                LoadPlanDestination dest = (LoadPlanDestination) result.get(i);
                data[i][0] = false;
                data[i][1] = dest.getDestination();
            }

            String[] cols = {"", "Destination finale"};
            DefaultTableModel model = new DefaultTableModel(data, cols) {
                @Override
                public Class<?> getColumnClass(int column) {
                    if (column == 1) {
                        return String.class;
                    } else {
                        return Boolean.class;
                    }
                }

            };
            destinations_table.setModel(model);

            //Set the Jtable column
            TableColumnModel columnModel = destinations_table.getColumnModel();
            columnModel.getColumn(0).setMaxWidth((int) (10 * 10000));
            columnModel.getColumn(1).setMaxWidth((int) (90 * 10000));

            destinations_table.setColumnModel(columnModel);

            this.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private org.jdesktop.swingx.JXDatePicker deliveryDatePicker;
    private javax.swing.JTable destinations_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ok_btn;
    // End of variables declaration//GEN-END:variables

}
